/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e1e0ff",
        "surface-container": "#eceef0",
        "tertiary-container": "#221eb5",
        "on-surface-variant": "#43474c",
        "surface-tint": "#4e6073",
        "on-tertiary-fixed": "#07006c",
        "on-primary": "#ffffff",
        "secondary": "#00677d",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#4cd6fb",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "primary-fixed": "#d1e4fb",
        "tertiary-fixed-dim": "#c0c1ff",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "on-secondary-container": "#005c70",
        "on-secondary-fixed-variant": "#004e5f",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b5c8df",
        "on-primary-fixed-variant": "#36485b",
        "inverse-primary": "#b5c8df",
        "on-tertiary-container": "#9b9eff",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "secondary-container": "#50d9fe",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c4c6cd",
        "outline": "#74777d",
        "primary-container": "#2c3e50",
        "tertiary": "#0c008e",
        "on-secondary-fixed": "#001f27",
        "on-primary-fixed": "#091d2e",
        "on-primary-container": "#96a9be",
        "primary": "#162839",
        "surface-container-low": "#f2f4f6",
        "error": "#ba1a1a",
        "secondary-fixed": "#b3ebff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "2xl": "48px",
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "sm": "8px",
        "container-max": "1280px",
        "base": "4px",
        "sidebar-width": "280px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "code-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
