"""
PRD Generation routes - integrates GTPlanner AI generation with web interface
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from uuid import uuid4
import logging

from gtplanner.web.database import get_session
from gtplanner.web.middleware import get_current_user
from gtplanner.web.models import User

logger = logging.getLogger(__name__)

router = APIRouter()


class PRDGenerationRequest(BaseModel):
    """Request for generating PRD from description"""
    description: str = Field(..., min_length=10, max_length=5000, description="Natural language description of the product requirements")
    language: str = Field(default="en", description="Language for generated PRD (en, zh, ja, es, fr, id)")
    context: Optional[str] = Field(None, max_length=2000, description="Additional context for PRD generation")


class PRDGenerationResponse(BaseModel):
    """Response from PRD generation"""
    task_id: str
    status: str
    message: str
    generated_content: Optional[Dict[str, Any]] = None


@router.post("/generate-prd")
async def generate_prd_stream(
    request: PRDGenerationRequest,
    current_user: User = Depends(get_current_user)
):
    """
    Generate PRD using GTPlanner AI agent
    Returns Server-Sent Events stream for real-time generation progress
    """
    task_id = str(uuid4())

    logger.info(f"Starting PRD generation for user {current_user.id}, task: {task_id}")

    async def event_generator():
        """Generate SSE events for PRD generation progress"""
        try:
            # Send initial event
            yield f"event: start\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"started\", \"message\": \"Initializing PRD generation...\"}}\n\n"

            # Prepare dialogue for GTPlanner agent
            system_prompt = f"""You are GTPlanner, an AI assistant that generates comprehensive Product Requirements Documents (PRDs) based on natural language descriptions.

Generate the PRD in the following JSON structure:
{{
  "sections": {{
    "overview": "Brief overview of the product/project",
    "background": "Background and context",
    "goals": "Goals and objectives",
    "scope": "Scope and boundaries",
    "stakeholders": "Key stakeholders",
    "features": "Core features and requirements",
    "timeline": "Estimated timeline and milestones",
    "resources": "Required resources",
    "risks": "Potential risks and mitigation strategies"
  }}
}}

Language: {request.language}

User description: {request.description}
"""
            if request.context:
                system_prompt += f"\n\nAdditional context: {request.context}"

            # Create AgentContextRequest for GTPlanner
            agent_request = AgentContextRequest(
                session_id=task_id,
                dialogue_history=[
                    {
                        "role": "system",
                        "content": system_prompt
                    },
                    {
                        "role": "user",
                        "content": f"Please generate a comprehensive PRD based on this description: {request.description}"
                    }
                ]
            )

            yield f"event: progress\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"generating\", \"message\": \"AI agent is analyzing requirements...\"}}\n\n"

            # Collect generated content
            generated_content = []

            # Stream the generation process (simplified version)
            try:
                # In a real implementation, this would connect to the SSE stream
                # For now, we'll simulate the generation process
                import asyncio
                await asyncio.sleep(1)  # Simulate processing time

                yield f"event: progress\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"analyzing\", \"message\": \"Analyzing product requirements...\"}}\n\n"
                await asyncio.sleep(1)

                yield f"event: progress\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"structuring\", \"message\": \"Structuring PRD sections...\"}}\n\n"
                await asyncio.sleep(1)

                yield f"event: progress\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"formatting\", \"message\": \"Formatting and validating content...\"}}\n\n"
                await asyncio.sleep(1)

                # For demonstration, create a basic structure
                # In production, this would use the actual GTPlanner agent response
                demo_content = {
                    "sections": {
                        "overview": f"Product based on: {request.description}",
                        "background": "This section would contain background information generated by GTPlanner AI.",
                        "goals": "Specific goals and objectives would be generated here.",
                        "scope": "Scope definition and boundaries would be detailed here.",
                        "stakeholders": "Key stakeholders and their roles would be identified.",
                        "features": "Core features and technical requirements would be specified.",
                        "timeline": "Implementation timeline and milestones would be outlined.",
                        "resources": "Required resources (team, technology, budget) would be listed.",
                        "risks": "Potential risks and mitigation strategies would be analyzed."
                    }
                }

                generated_content.append(demo_content)

                # Convert to JSON for the response
                import json
                content_json = json.dumps(demo_content)
                yield f"event: complete\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"completed\", \"message\": \"PRD generation completed!\", \"content\": {content_json}}}\n\n"

                logger.info(f"PRD generation completed for task: {task_id}")

            except Exception as e:
                logger.error(f"Error in PRD generation: {str(e)}")
                yield f"event: error\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"error\", \"message\": \"Generation failed: {str(e)}\"}}\n\n"

        except Exception as e:
            logger.error(f"Error in event generator: {str(e)}")
            yield f"event: error\ndata: {{\"task_id\": \"{task_id}\", \"status\": \"error\", \"message\": \"Stream error: {str(e)}\"}}\n\n"

    return event_generator()


@router.post("/generate-prd-sync", response_model=PRDGenerationResponse)
async def generate_prd_sync(
    request: PRDGenerationRequest,
    current_user: User = Depends(get_current_user)
):
    """
    Synchronous PRD generation (simplified version)
    Returns complete generated PRD content
    """
    task_id = str(uuid4())

    logger.info(f"Starting sync PRD generation for user {current_user.id}")

    try:
        # Simulate PRD generation (in production, this would call the actual GTPlanner agent)
        import asyncio
        await asyncio.sleep(2)  # Simulate processing time

        # For demonstration, create a structured response
        generated_content = {
            "sections": {
                "overview": f"Product Overview: {request.description}",
                "background": "Background and context information would be generated by GTPlanner AI based on the provided description.",
                "goals": "Goals and objectives would be analyzed and defined based on the requirements.",
                "scope": "Scope boundaries and inclusions/exclusions would be clearly defined.",
                "stakeholders": "Key stakeholders including users, team members, and external parties would be identified.",
                "features": "Core features and functional requirements would be detailed and prioritized.",
                "timeline": "Implementation timeline with key milestones and deliverables would be outlined.",
                "resources": "Required resources including team, technology stack, infrastructure, and budget would be specified.",
                "risks": "Potential technical, business, and project risks would be identified with mitigation strategies."
            }
        }

        logger.info(f"Sync PRD generation completed for task: {task_id}")

        return PRDGenerationResponse(
            task_id=task_id,
            status="completed",
            message="PRD generated successfully",
            generated_content=generated_content
        )

    except Exception as e:
        logger.error(f"Error in sync PRD generation: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PRD generation failed: {str(e)}"
        )


@router.post("/generate-and-save")
async def generate_and_save_prd(
    workspace_id: str,
    request: PRDGenerationRequest,
    current_user: User = Depends(get_current_user),
    session: Session = Depends(get_session)
):
    """
    Generate PRD and automatically save it to the workspace
    Combines generation and creation in one operation
    """
    task_id = str(uuid4())

    logger.info(f"Starting generate-and-save for workspace {workspace_id}")

    try:
        # Generate PRD content
        generation_response = await generate_prd_sync(request, current_user)

        if generation_response.status != "completed" or not generation_response.generated_content:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="PRD generation failed"
            )

        # Create PRD in workspace
        from gtplanner.web.services.prd_service import prd_service

        # Generate a title from the description
        title = request.description.split('.')[0][:100]  # First sentence, max 100 chars

        prd = prd_service.create_prd(
            session=session,
            workspace_id=workspace_id,
            title=title,
            content=generation_response.generated_content,
            created_by=current_user.id
        )

        logger.info(f"PRD created successfully: {prd.id}")

        return {
            "task_id": task_id,
            "status": "completed",
            "message": "PRD generated and saved successfully",
            "prd_id": prd.id,
            "prd_title": prd.title,
            "prd_version": prd.version
        }

    except Exception as e:
        logger.error(f"Error in generate-and-save: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate and save PRD: {str(e)}"
        )